### ISSUE TITLE
TLSv1 explicitly needed for TP6X_RAC_16K

### ISSUE THREAD

**Issue by BZoli97** [atxbyea/samsungrac#101]
Hello,

I have an AC "TP6X_RAC_16K" and from HA 2024.07 it is stops to working because still using TLSv1

`ERROR (MainThread) [custom_components.climate_ip.climate] Request result exception: HTTPSConnectionPool(host='xxx.xxx.xxx.xxx', port=8888): Max retries exceeded with url: /devices (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))`

I saw the set_ciphers was already set to "ALL:@SECLEVEL=0", and seemingly worked till now with openssl3.x but from now for me it is also require minimum_version ssl.TLSVersion.TLSv1

**Comment by BZoli97** [comment]
I just checked the blame and missed this line was alreday there before.  I just added a similar PR, but in this case that is not needed

**Comment by samuelecarpene** [comment]
same problem here
