### ISSUE TITLE
Installed via HACS, got the tokens, but log is full of strange errors

### ISSUE THREAD

**Issue by goncalorijo** [atxbyea/samsungrac#105]
Hello,

I'm using HAOS, on a proxmox VM. 
Latest version:

> Core 2024.7.4
> Supervisor 2024.06.2
> Operating System 12.4
> Frontend 20240710.0
> climate_ip 6.2 installed via HACS

This is what i'm currently seeing on the logs:
```
Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/connection_request.py:137
integration: climate_ip ([documentation](https://github.com/atxbyea/samsungrac), [issues](https://github.com/atxbyea/samsungrac/issues))
First occurred: 11:13:22 PM (7 occurrences)
Last logged: 11:14:41 PM

Request result exception: HTTPSConnectionPool(host='192.168.1.14', port=8888): Max retries exceeded with url: /devices (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))

```

I've seen the link on the bottom of the readme page (https://github.com/atxbyea/samsungrac/releases/tag/3.5.3) but it seems that it was solved on a previous release.

I've tried to add a thermostat to a dashboard but i just get a non working widget.

Any recomendation?

**Comment by wifi75** [comment]
consider this project....

https://github.com/lanwin/esphome_samsung_ac

**Comment by goncalorijo** [comment]
Thank you @wifi75 .

I've used it and everything is working correctly.
