### ISSUE TITLE
Support Samsung AC with Wind Free mode

### ISSUE THREAD

**Issue by kleju00** [atxbyea/samsungrac#14]
Some air conditioning models from Samsung have a Wind Free mode. To handle it you need to add the following mode and special mode in samsungrac.yaml

` 'Wind Free': { value : 'Comode_Nano', connection: { params: { json: { "options": ["Comode_Nano"] } } } }`

**Comment by atxbyea** [comment]
@kleju00 could you submit it as a PR and I'll review and commit it

**Comment by atxbyea** [comment]
Like this @kleju00 https://github.com/atxbyea/samsungrac/pull/15 ?

**Comment by kleju00** [comment]
> Like this @kleju00 #15 ?

Yes exactly.

**Comment by atxbyea** [comment]
Release 3.3 should fix this, closing issue
