### ISSUE TITLE
V. 3.5 don’t work

### ISSUE THREAD

**Issue by KameDomotics** [atxbyea/samsungrac#21]

**Comment by KameDomotics** [comment]
After the update from 3.4 to 3.5, the air conditioning entity has disappeared.

I downgraded to version 3.4 and the entity is back to being available.

**Comment by ishioni** [comment]
There's a second call to async_update wrapped in create_task that needs to be reverted. I'll prepare a PR when I get home

**Comment by dapuzz** [comment]
Same issue here with old 2878 protocol:

`2020-12-28 10:07:44 ERROR (MainThread) [homeassistant.components.climate] climate_ip: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 459, in async_device_update
    task = self.hass.async_create_task(self.async_update())  # type: ignore
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 391, in async_create_task
    task: asyncio.tasks.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)`

Let me know if I can help in some way
Thank you

**Comment by KameDomotics** [comment]
> There's a second call to async_update wrapped in create_task that needs to be reverted. I'll prepare a PR when I get home
> 
> Edit: actually no, this is something different. Serves me right reading on a phone. Can you tell us which device?

Samsung AR7000 (samsungrac 8888)

**Comment by massive** [comment]
Same here. Started happening after upgrading to Home Assistant 2020.12.1 from 2020.12.0.

**Comment by atxbyea** [comment]
3.5.1 fixes this issue
