### ISSUE TITLE
Latest Release doesn't show the entities anymore.

### ISSUE THREAD

**Issue by Jens-Wymeersch** [atxbyea/samsungrac#22]
@atxbyea Version 3.5 seems to be off : 
![image](https://user-images.githubusercontent.com/70786498/103286034-44c60300-49e8-11eb-903c-d2ef901e7d3a.png)
This is not the case in 3.4 with the changes made by Pierre. 
![image](https://user-images.githubusercontent.com/70786498/103286380-b9993d00-49e8-11eb-9466-e61b390ad1c1.png)

**Comment by atxbyea** [comment]
I noticed the same and had to revert, but I don't have time to fix it until after Christmas

**Comment by KameDomotics** [comment]
I have same problem with 3.5 and samsungrac

**Comment by Jens-Wymeersch** [comment]
@KameDomotics I highly recommend looking at the fix from Pierre https://github.com/atxbyea/samsungrac/issues/5#issuecomment-749785206

**Comment by KameDomotics** [comment]
> @KameDomotics I highly recommend looking at the fix from Pierre [#5 (comment)](https://github.com/atxbyea/samsungrac/issues/5#issuecomment-749785206)

can you show me the complete modification you made? (Screenshot)
Thanks

**Comment by KameDomotics** [comment]
![6DBF5143-AF8F-4B58-B65F-15B7B7F19A53](https://user-images.githubusercontent.com/47695661/103312150-75c02b00-4a1c-11eb-9228-e6ea85438c2a.jpeg)

Don’t work!

**Comment by Jens-Wymeersch** [comment]
Hi @KameDomotics 
I deleted those 4 lines and changed them with what Pierre gave, it is a hell of a difference for me

![image](https://user-images.githubusercontent.com/70786498/103313129-c38e6080-4a27-11eb-81cc-bd2cd73bd2ec.png)

**Comment by KameDomotics** [comment]
I have another problem with my climate:
it sometimes disconnects from the wifi network, and when HomeAssistant "call" it and does not find it reachable, it continually creates errors like this:

`Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/connection_request.py:113
Integration: climate_ip (documentation, issues) 
First occurred: 21:59:55 (2 occurrences) 
Last logged: 22:00:08

Request execution failed. Stack trace: `



Is there any way to override this check?
If the air conditioner is not reachable, I don't want the error...

**Comment by atxbyea** [comment]
this issue has been resolved
