### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'climate_ip'.

### ISSUE THREAD

**Issue by Nick398** [atxbyea/samsungrac#26]
No 'version' key in the manifest file for custom integration 'climate_ip'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'climate_ip'

https://developers.home-assistant.io/docs/creating_integration_manifest/

Just a WARNING now, but it seems they will prevent it from running in the future.

**Comment by atxbyea** [comment]
Fixed in 3.5.2, thanks @Nick398

**Comment by Nick398** [comment]
Thanks mate!
