### ISSUE TITLE
Integration no longer loads in 2021.6

### ISSUE THREAD

**Issue by buzurk26** [atxbyea/samsungrac#29]
Hi

Component no longer loads in 2021.6

Taken form release notes
```
Custom integrations (custom_components) - https://www.home-assistant.io/blog/2021/06/02/release-20216/#breaking-changes
As mentioned in every release since 2021.3, custom integrations will require a version key in their manifest file.

As of this release, if that version key is missing in the manifest, the custom integration will no longer be loaded.

For more details see our developer blog about it
```

Will the version key be provided for this integration (assuming that is whats needed) ? 

Thanks

**Comment by piolohm** [comment]
The version is already present in the manifest.json ("version": "3.5.2").
The problem should be somwhere else.

Anybody have maybe solved the problem?

Thanks

**Comment by Uffepuff** [comment]
I have the same issue, the component does not load. Error msg from validate config:

Platform error climate.climate_ip - Integration 'climate_ip' not found.

Nothing in the log as I can find. Version is ok in manifest.json. HA 2021.6.5

The component have been working like a charm until update of HA.

Thanks,
Uffe

**Comment by Uffepuff** [comment]
After some other edits, restarts and solving some not related braking changes, up and running again - unfortunately without understanding of what solved the problem. Strange.

**Comment by piolohm** [comment]
Hi @Uffepuff,
this is a great news!
I've tryed to:
- reinstall again the component --> no works
- perform a dos2unix in files having the windows carriadge return (^M) --> no works
- add a new lines il last row in files not ending with the return --> no works
- delete the subfolder __pycache__ (automatically recreated with a restart) --> no works

Are you able to tell us where did you performed "some edits"?
Would you also try to share the files of your custom_components/climate_ip folder?

Thanks,
Pierpaolo

**Comment by piolohm** [comment]
Here an update:
i've enabled the debug (debug: True) in the configuration parameter of the device and found in the log an error connecting to the IP

```
 INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 192.168.0.82:2878
 INFO (MainThread) [custom_components.climate_ip.climate] Sending command failed
```

So looking at the wifi led of the split it was off 😢 .
Restarting the access point (working for other connected devices) now i've the split online and the climate_ip component is working!

```
INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 192.168.0.82:2878
INFO (MainThread) [custom_components.climate_ip.climate] Reading data from socket...
INFO (MainThread) [custom_components.climate_ip.climate] Response: DPLUG-1.6
INFO (MainThread) [custom_components.climate_ip.climate] Reading data from socket...
```

So it was really strange, the power of the AC was switched off and on more than one time in past days; my wifi network was working properly for other clients. Only restarting the AP was the right solution.

Now my 3 split are back again in HA :D
![image](https://user-images.githubusercontent.com/71259754/122554928-e2b29600-d039-11eb-9fbc-b1b60427a81d.png)

Hope this can help,
Pierpaolo

**Comment by Uffepuff** [comment]
> Hi @Uffepuff,
> this is a great news!
> I've tryed to:
> 
> * reinstall again the component --> no works
> * perform a dos2unix in files having the windows carriadge return (^M) --> no works
> * add a new lines il last row in files not ending with the return --> no works
> * delete the subfolder **pycache** (automatically recreated with a restart) --> no works
> 
> Are you able to tell us where did you performed "some edits"?
> Would you also try to share the files of your custom_components/climate_ip folder?
> 
> Thanks,
> Pierpaolo

Sorry for late reply. Unfortunately I cannot remember the edits other than removal of some deprecated yaml configs (Tuya and some more) in all resulting in several restarts. I also commented out and edited the climate_ip config in config.yaml during my testing. The contents in my climate_ip folder is only the latest Github from this repo. 
Thanks, U

**Comment by atxbyea** [comment]
appears to have been local wifi issues only, not related to the component, thanks for the updates
