### ISSUE TITLE
Certificate issues (again)

### ISSUE THREAD

**Issue by d3m3trius** [atxbyea/samsungrac#40]
#38 doesn't work for my AC that need "ALL:@SECLEVEL=0" to works correctly.

So, looking at the commits and issues history, it looks like there are some devices/OS that need:
sslContext.set_ciphers("ALL:@SECLEVEL=0")
and other that need:
sslContext.set_ciphers("HIGH:!DH:!aNULL")

The solution may be adding a config parameter with a default value and the possibility to change it.

**Comment by atxbyea** [comment]
Should be fixed in 4.1 thanks to @CookingBlight !
