### ISSUE TITLE
HA Update seems to have broken things

### ISSUE THREAD

**Issue by ATuxford** [atxbyea/samsungrac#44]
Hi,

Since upgrading to HA core-2022.5.4 I get the below error as climate tries to add in climate_ip. It seems to fall over because HVACMode is null. I am not a programmer so I'm not sure where to look to see where this is set.

Thanks

Andrew

`Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 17:29:03 (3 occurrences)
Last logged: 17:29:11

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode`

**Comment by smartekIT** [comment]
I confirm this with core-2022.5.5 too.

**Comment by smartekIT** [comment]
I think we got affected by the following changes in HA:
https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation/
https://developers.home-assistant.io/blog/2022/05/03/constants-deprecations/

I checked them against climate.py file and clearly see that most of these need to be changed accordingly.

Hope some one will look into this soon.

Thanks heaps.

**Comment by smartekIT** [comment]
@atxbyea can you please help us in this? we have HA update paused because of this, if we update then the whole thing breaks and we can't control AC anymore. Thanks heaps

**Comment by CookingBlight** [comment]
@smartekIT I got the same errors as you and I managed to fix it on my installation.

After adding some error checking and doing some digging I found out it was caused by an SSL error when a MD5 cerficiate is used. I believe these errors are now coming to light because of new libraries used with python 3.10 with a higher degree of security set by default. I have created a fork and implemented a fix that worked for me.

I also want to note that the token fetcher found elsewhere also fails when using python 3.10.

**Comment by smartekIT** [comment]
Thanks heaps @CookingBlight , I appreciate your help.

**Comment by smartekIT** [comment]
@CookingBlight how about the constants deprecations in HA mentioned here:
https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation/
https://developers.home-assistant.io/blog/2022/05/03/constants-deprecations/
and I believe they still there in our code ?!

**Comment by CookingBlight** [comment]
@smartekIT I had a look at it and I have replaced the deprecated constants that I found.

If the fix I implemented earlier doesn't work please let me know.

**Comment by smartekIT** [comment]
@CookingBlight , you such a legend mate. I can confirm that your fork works fine with v2022.6.7 :)

**Comment by CookingBlight** [comment]
@smartekIT thats really good to hear! Glad I could be of some help :)

**Comment by wifi75** [comment]
sorry but what to do, I just didn't understand what I need to change ...

**Comment by CookingBlight** [comment]
@wifi75 I made some changes to [connection_request.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/connection_request.py) to solve this on my installation. You can either download the complete fork or just that file. Make a backup of the old file in case the changes I made doesn't work.

I also made some changes to [climate.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/climate.py) to get rid of some deprecated constants.

**Comment by giig982** [comment]
@CookingBlight i removed @atxbyea repository and imported yours in HACS, in order to use your component in HA 2022.6.7, but  anyway I have those errors:

`Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Termostato
First occurred: 12:14:32 (2 occurrences)
Last logged: 12:14:32

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode `

To have more context: I own 3 old generation Samsung AC units, available at port 2878.

Before using your fork, I had 2 of 3 AC out of service. With your fork, only 1 of 3 is out of service.

**Comment by CookingBlight** [comment]
@giig982 the fix I implemented only applies to the newer models as far as I could tell. I will have a look at the older model code and see if there is an easy fix.

**Comment by CookingBlight** [comment]
@giig982 Try to replace sslContext.set_ciphers("HIGH:!DH:!aNULL") on line 248 in samsung_2878.py with sslContext.set_ciphers("ALL:@SECLEVEL=0")

**Comment by CookingBlight** [comment]
@giig982 could you turn on debugging in the configuration file?

**Comment by giig982** [comment]
> @giig982 could you turn on debugging in the configuration file?

I just made the change to connection_request.py and put custom_components.climate_ip.climate: debug in configuration.yaml.

Let me restart HA and I'll tell your the result.

**Comment by Anzic23** [comment]
the following helped me:


> I made some changes to [connection_request.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/connection_request.py) to solve this on my installation. You can either download the complete fork or just that file. Make a backup of the old file in case the changes I made doesn't work.
> 
> I also made some changes to [climate.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/climate.py) to get rid of some deprecated constants.

and:



> You could try to change ssl_context.set_ciphers("ALL:@SECLEVEL=0") on line 29 in [connection_request.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/connection_request.py) from my fork with ssl_context.set_ciphers("HIGH:!DH:!aNULL")

**Comment by CookingBlight** [comment]
Thanks for the information @Anzic23 . I think I will implement an option for setting siphers in the configuration file.

**Comment by atxbyea** [comment]
Feel free to submit PRs if you have fixes that can be useful for other people @CookingBlight @Anzic23 👍

**Comment by wifi75** [comment]
hello, I didn't understand what needs to be done, I no longer have my climate in HA.
what changes should i make?

**Comment by giig982** [comment]
> It is quite difficult to debug the problem with 3 units connected at the same time. If you implement the initial fix from my fork where you had two units working, could you set up a configuration with the one unit alone that doesnt work? This way we can ensure that any changes doesn't break a different unit. It might be that the units require different siphers as stated in #40
> 
> In that case I will implement a setting in the configuration file.

Hi @CookingBlight, today I reconfigured each WiFi connection on the ACs that didn't connect to HA, as they didn't appear also in the old Samsung App, and now everything is working fine again! So, to me, your fork is working correctly with HA 2022.6.7.

**Comment by wifi75** [comment]
> @wifi75 I made some changes to [connection_request.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/connection_request.py) to solve this on my installation. You can either download the complete fork or just that file. Make a backup of the old file in case the changes I made doesn't work.
> 
> I also made some changes to [climate.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/climate.py) to get rid of some deprecated constants.

not working.....

**Comment by Poncharello** [comment]
Version 4.1 now is working also for me!!!
Thank you very much guys, you are my heroes! :)

**Comment by rerpires** [comment]
> the following helped me:
> 
> > I made some changes to [connection_request.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/connection_request.py) to solve this on my installation. You can either download the complete fork or just that file. Make a backup of the old file in case the changes I made doesn't work.
> > I also made some changes to [climate.py](https://github.com/CookingBlight/samsungrac/blob/master/custom_components/climate_ip/climate.py) to get rid of some deprecated constants.
> 
> and:
> 
> > replace sslContext.set_ciphers("HIGH:!DH:!aNULL") on line 248 in samsung_2878.py with sslContext.set_ciphers("ALL:@SECLEVEL=0")

copied your new code and still getting the same issue: 

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Climate (documentation, issues)
First occurred: 00:43:10 (6 occurrences)
Last logged: 00:43:41

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: '' is not a valid HVACMode


what more can I do ? 

running 2022.7.3
