### ISSUE TITLE
New certificate and fix for cypher configuration

### ISSUE THREAD

**Issue by lucadjc** [atxbyea/samsungrac#66]
Hi,
i created a new releases with 2 main changes:
- new certificate from Samsung with expiration date 2060
- change on samsung_2878.py the cyphersuite setting as following (in bold the new rows). 

This is allowing my home setting to work properly both with C/A that are requiring the certificates and the once without. 

def create_connection(self):
        sslSocket = None
        cfg = self._cfg
        self.logger.info("Creating ssl context")
        sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        self.logger.info("Setting up ciphers")
        sslContext.set_ciphers("HIGH:!DH:!aNULL")
        self.logger.info("Setting up verify mode")
        sslContext.verify_mode = (
            ssl.CERT_REQUIRED if cfg.cert is not None else ssl.CERT_NONE
        )
        if cfg.cert is not None:
            **sslContext.set_ciphers("ALL:@SECLEVEL=0")**
            self.logger.info("Setting up verify location: {}".format(cfg.cert))
            sslContext.load_verify_locations(cafile=cfg.cert)
            self.logger.info("Setting up load cert chain: {}".format(cfg.cert))
            sslContext.load_cert_chain(cfg.cert)

**Comment by lucadjc** [comment]
ciao, PR created

**Comment by atxbyea** [comment]
thanks a lot @lucadjc
