### ISSUE TITLE
problem version 5.0 samsung_2878

### ISSUE THREAD

**Issue by wifi75** [atxbyea/samsungrac#69]
hello I have two samsung type *samsung_2878* after update from 4.3 to 5.0

the integration no longer works, it seems that there is no longer a connection

found problem:

I renamed to in custom folder, ac14k_m.pem

**Comment by cannos88** [comment]
the problem seems to be related to the certificate called ac14k_m_new.pem
Renaming the certificate seems to work

**Comment by Anzic23** [comment]
Great solution! It needs to be added to the description when updating, or corrected, so that this does not happen, and you do not have to edit the config or rename the file.
