### ISSUE TITLE
MIM-H03 - timeout issues

### ISSUE THREAD

**Issue by rgogada** [atxbyea/samsungrac#75]
I have been having timeout issues with MIM-H03 from last couple of weeks. This has been working with out any issues on 5.1 so something must have changed on samsung server side. Does anyone else having any timeout issues with MIM-H03?

ERROR:
----------
Request result exception: HTTPSConnectionPool(host='192.168.1.29', port=8888): Read timed out. (read timeout=15)

**Comment by jay0xy** [comment]
Does your device appear offline in SmartThings?

**Comment by rgogada** [comment]
it seems to be working fine from smartthings app.

**Comment by rgogada** [comment]
Also, just noticed it is working in homeassistant as well. I made no
changes so something on samsung serverside.

**Comment by jay0xy** [comment]
Yep the issue self corrected 2 days ago
Something Samsung server side related
