### ISSUE TITLE
5.2 fails unique_id

### ISSUE THREAD

**Issue by thomas70** [atxbyea/samsungrac#77]
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5

Logger: homeassistant.components.climate
Source: custom_components/climate_ip/climate.py:261
Integration: Klima ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 22:07:36 (2 occurrences)
Last logged: 22:07:36

Error adding entities for domain climate with platform climate_ip
Error while setting up climate_ip platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 590, in _async_add_entity
    if entity.unique_id is not None:
       ^^^^^^^^^^^^^^^^
  File "/config/custom_components/climate_ip/climate.py", line 261, in unique_id
    self._unique_id = "climate_ip_" + name_value
                      ~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by lucadjc** [comment]
Please can you text the setting added into configuration.yaml ?

**Comment by thomas70** [comment]
- platform: climate_ip
  config_file: 'samsung_2878.yaml'
  ip_address: '192.168.10.62'
  token: 'token'
  cert: 'ac14k_m.pem' #set as '' to skip certificate verification
  mac: 'bc:8c:cd:xx:xx:xx'
  debug: True

**Comment by lucadjc** [comment]
assign these attributes too

name: 'Name that you prefer'
poll: True

let me know the results

ciao

**Comment by thomas70** [comment]
name: 'Name that you prefer'
poll: True

in the configuration solved the issue
