### ISSUE TITLE
Cannot establish connection to AC unit

### ISSUE THREAD

**Issue by Alexciao** [atxbyea/samsungrac#78]
My error is:

2023-09-03 15:14:26.795 ERROR (SyncWorker_9) [custom_components.climate_ip.climate] Creating socket failed!
2023-09-03 15:14:27.402 ERROR (SyncWorker_6) [custom_components.climate_ip.climate] Error: Traceback (most recent call last):
File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection
sslSocket.connect((cfg.host, cfg.port))
File "/usr/local/lib/python3.11/ssl.py", line 1379, in connect
self._real_connect(addr, False)
File "/usr/local/lib/python3.11/ssl.py", line 1370, in _real_connect
self.do_handshake()
File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)

I'm sorry if this is obvious lol, my token and MAC addresses are correct.

**Comment by lucadjc** [comment]
Which version are you running?
can you text the configuration.yaml details?

**Comment by Alexciao** [comment]
> Which version are you running? can you text the configuration.yaml details?

Running HASS 2023.8.4 inside a Docker container.
Integration version is 5.2

**Comment by lucadjc** [comment]
please text the configuration.yaml

**Comment by Alexciao** [comment]
> please text the configuration.yaml

Edited my reply

**Comment by lucadjc** [comment]
Try this config, save, restart HA and text the logging
  - platform: climate_ip
    config_file: '/config/custom_components/climate_ip/samsung_2878.yaml'
    ip_address: 192.168.1.20
    token: value
    device_id: as token
    cert: 'ac14k_m.pem'
    mac: value
    name: 'name'
    poll: True
    debug: True

**Comment by Alexciao** [comment]
I'll try

**Comment by Alexciao** [comment]
Looks like it works now, I'll get back here if I have any more issues. Thanks!

**Comment by lucadjc** [comment]
i suggest to turn off debug with 
debug: **False**

**Comment by Alexciao** [comment]
Looks like the Web UI does not load.
I restart HASS, get to the phase where every integration loads and then the Web UI refuses to function, with no errors in logs.

**Comment by Alexciao** [comment]
Looks like it was the tado integration
