### ISSUE TITLE
samsungrac is not fully supported with python 3.11

### ISSUE THREAD

**Issue by jpakanen2** [atxbyea/samsungrac#80]
The problem is at least in this file: https://github.com/atxbyea/samsungrac/blob/master/custom_components/climate_ip/climate.py

row 167:  await asyncio.wait(update_tasks, loop=hass.loop)
Parameters provided for asyncio.wait are not supported anymore.

The fix is this: 

replace line 164 like this:
original: update_tasks.append(device.async_update_ha_state(True))
updated:  update_tasks.append(asyncio.create_task(device.async_update_ha_state(True)))

and
line 167:
original:  await asyncio.wait(update_tasks, loop=hass.loop)
updated: await asyncio.wait(update_tasks)

**Comment by jpakanen2** [comment]
In addition, the changed portion is used at least when functions are triggered via HA automation.

**Comment by Blodskjegg** [comment]
I cant get my AC unit to show up in HA at all after the recent update :(

**Comment by jpakanen2** [comment]
> I cant get my AC unit to show up in HA at all after the recent update :(

I had the same problem. I updated latest sources from this project and helped.

**Comment by Blodskjegg** [comment]
Got it working now with what you updated and also had to edit line 261 in climate.py from
self._unique_id = "climate_ip_" + name_value
to
self._unique_id = "climate_ip_" + str(name_value)

**Comment by atxbyea** [comment]
Merged into a new release
