### ISSUE TITLE
2878 component broken after python3.11

### ISSUE THREAD

**Issue by starbreaker667** [atxbyea/samsungrac#82]
Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/samsung_2878.py:289
Integration: climate_ip ([documentation](https://github.com/atxbyea/samsungrac), [issues](https://github.com/atxbyea/samsungrac/issues))
First occurred: 21.35.15 (2 occurrences)
Last logged: 21.35.18

Error: Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 283, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.11/ssl.py", line 1412, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.11/ssl.py", line 1399, in _real_connect super().connect(addr) OSError: [Errno 113] Host is unreachable

**Comment by jpakanen2** [comment]
Are you using the latest sources?

**Comment by atxbyea** [comment]
Works fine on HA 2024.01 here.
