### ISSUE TITLE
Deprecated constant HVAC_MODE_OFF

### ISSUE THREAD

**Issue by dapuzz** [atxbyea/samsungrac#83]
As per startup log:

`WARNING (MainThread) [homeassistant.components.climate] HVAC_MODE_OFF was used from climate_ip, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead`

Is there any plan to update?

Thank you

**Comment by atxbyea** [comment]
I'll need to get around to it, on my agenda.
