### ISSUE TITLE
samsung old version port 8888 not working

### ISSUE THREAD

**Issue by wifi75** [atxbyea/samsungrac#89]
Hello after last update from 5.3 my old samsung ac 8888 not working

**Comment by wifi75** [comment]
hello I try do switch off my AC and after reset now working with last version.

sorry

**Comment by lawrencelnm** [comment]
> hello I try do switch off my AC and after reset now working with last version.
> 
> sorry

Hi there. What is your AC model ?
And is it working or not ? I'm confused with the response.
