### ISSUE TITLE
Execute condition found, error while evaluating, executing command

### ISSUE THREAD

**Issue by GroundAttack** [atxbyea/samsungrac#99]
This error originated from a custom integration.

Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/connection_request.py:100
integration: climate_ip (documentation, issues)
First occurred: 10:27:50 AM (1 occurrences)
Last logged: 10:27:50 AM

Execute condition found, error while evaluating, executing command

Happened just after installing the latest version.

**Comment by GroundAttack** [comment]
This might help with diagnosis:
This error originated from a custom integration.

Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/connection_request.py:137
integration: climate_ip (documentation, issues)
First occurred: 10:23:29 AM (784 occurrences)
Last logged: 1:37:20 PM

Request result exception: HTTPSConnectionPool(host='192.168.1.93', port=8888): Max retries exceeded with url: /devices (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))
Request result exception: HTTPSConnectionPool(host='192.168.1.93', port=8888): Max retries exceeded with url: /devices/0/temperatures/0 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))
Request result exception: HTTPSConnectionPool(host='192.168.1.93', port=8888): Max retries exceeded with url: /devices/0 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))
Request result exception: HTTPSConnectionPool(host='192.168.1.93', port=8888): Max retries exceeded with url: /devices/0/mode (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1000)')))

**Comment by elvirdz** [comment]
I got same problem with climate ip 6.2 with 6.0.1 there is no problem

**Comment by cannos88** [comment]
I confirm, with this fix it works and I see no errors

**Comment by GroundAttack** [comment]
Yea! Fast work!
Thank you.
